### ISSUE TITLE
cygpath roundtrip produces double slash: cygpath -u ``cygpath -m /`` -> `//`

### ISSUE THREAD

**Issue by Kojoley** [msys2/Cygwin#112]
### Description

cygpath roundtrip produces double slash

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19045.2130]

### Expected behavior

/

### Actual behavior

//

### Repro steps

```sh
$ cygpath -u `cygpath -m /`
//
```

**Comment by 1480c1** [comment]
You may want to open this issue with cygwin as cygpath is provided by them

**Comment by dscho** [comment]
@Kojoley could you download https://github.com/msys2/msys2-runtime/suites/9192286285/artifacts/428678831, replace your `/usr/bin/msys-2.0.dll` with the one included in that `.zip` (you will have to stop all MSYS processes before you can do that because that DLL would otherwise be in use) and confirm that the fix works?

**Comment by Kojoley** [comment]
> @Kojoley could you download [msys2/msys2-runtime/suites/9192286285/artifacts/428678831](https://github.com/msys2/msys2-runtime/suites/9192286285/artifacts/428678831), replace your `/usr/bin/msys-2.0.dll` with the one included in that `.zip` (you will have to stop all MSYS processes before you can do that because that DLL would otherwise be in use) and confirm that the fix works?

It does work, thanks!
