### ISSUE TITLE
Color output not working when using Windows Terminal with Atlas Engine renderer

### ISSUE THREAD

**Issue by aloebs29** [msys2/Cygwin#151]
Windows Terminal
Version: 1.16.10261.0

I'm using MSYS2 under Windows Terminal as described here: https://www.msys2.org/docs/terminals/

Windows terminal has a setting under "Profiles" -> "Defaults" (or select the profile you're using) -> "Advanced" -> "Use the new text renderer ('AtlasEngine')" (or in the JSON, `"useAtlasEngine" = true` under the profile's settings).

If this setting is enabled, terminal coloring no longer works (only with my MSYS2 profiles).

With default rendering:
![image](https://user-images.githubusercontent.com/25024170/231901358-862c2a74-244a-479e-8716-8ff9cf14d4a5.png)

With Atlas Engine rendering:
![image](https://user-images.githubusercontent.com/25024170/231901407-5c9faf00-1a74-4592-9c4f-c0e5972da788.png)

For some background/context here, I'm trying to get visible cursor highlighting in vim on windows terminal. The new renderer in windows terminal has a workaround/fix that the default does not: https://github.com/microsoft/terminal/issues/9610#issuecomment-1441144003

**Comment by lhecker** [comment]
This isn't a bug in msys2, but rather due to Windows Terminal: https://github.com/microsoft/terminal/issues/13989
The reason it happens is described here: https://github.com/microsoft/terminal/issues/13989#issuecomment-1248034492
If you're using Source Code Pro (the @ in your font does look very similar), simply upgrading your font will fix the issue until I fix the text renderer.

**Comment by aloebs29** [comment]
Thank you very much for the help, and good catch! Indeed, my MSYS2 profiles are the only ones that use Source Code Pro. Changing the font to Cascadia fixes the issue.
