### ISSUE TITLE
error when caling msys2_shell.cmd from WSL

### ISSUE THREAD

**Issue by alanlivio** [msys2/Cygwin#161]
I received the following error when calling msys2_shell.cmd from WSL
```
alan@elendil:~$ cmd.exe /mnt/c/msys64/msys2_shell.cmd -defterm -mingw64 -no-start -use-full-path -here
'\\wsl.localhost\Ubuntu\home\alan'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

**Comment by Biswa96** [comment]
Try this instead

```
 cmd.exe /c "C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -use-full-path -here"
```

**Comment by alanlivio** [comment]
many thanks @Biswa96 but same behavior.
```
alan@elendil:~
$  cmd.exe /c "C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -use-full-path -here"
'\\wsl.localhost\Ubuntu\home\alan'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

**Comment by Biswa96** [comment]
I am not sure why it is not working. But it's working in my system.

![image](https://github.com/msys2/msys2-runtime/assets/31443074/1fc5bfbc-c147-441c-9f5b-e40ff22973c4)

**Comment by sskras** [comment]
> I am not sure why it is not working. But it's working in my system.

@Biswa96, are you sure you shared the right screenshot?
The error looks the same as in @alanlivio's comment.

**Comment by Biswa96** [comment]
The message in screenshot is _not_ an error. It is expected behaviour for Command Prompt.

**Comment by alanlivio** [comment]
Thanks again. Yes. I was referring to the message "CMD.EXE started...".
At least, is there a way to say which directory msys2 should open (instead of /c/Windows)?

**Comment by Biswa96** [comment]
> At least, is there a way to say which directory msys2 should open (instead of /c/Windows)?

Use `-where` option with that command. For example,

```
 cmd.exe /c "C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -use-full-path -where C:\Windows\SystemResources\ShellComponents\pris"
```

**Comment by Biswa96** [comment]
`msys64\msys2_shell.cmd /?` command shows various options and their uses.

**Comment by alanlivio** [comment]
Many thanks. I will close the issue.

**Comment by sskras** [comment]
@alanlivio, you can also use UNC path for `-where` I guess.

I tried them in pure MSYS2 environment, and they work:
![image](https://github.com/msys2/msys2-runtime/assets/7887758/4e102106-1fdf-4480-9a16-cdcc264fda5a)

Via: https://stackoverflow.com/questions/10233330/cygwin-file-copy-to-unc-share/10235880#10235880

**Comment by Biswa96** [comment]
The "UNC paths are not supported" warning is coming from WSL and Windows path conversion. cygwin or msys2 is not related to that. The current directory in WSL is `~` i.e. home directory. It translates to `\\wsl.localhost\Ubuntu\home\alan` in OP's case.

The above warning can be resolved when the current working directory is a Windows directory. For example, in this screenshot, I invoked the msys2_shell.cmd script in `C:\` directory i.e. `/mnt/c/` in WSL by-default. And it does not show the warning message.

![image](https://github.com/msys2/msys2-runtime/assets/31443074/a4386b80-ba01-4965-8e8f-bf84ed0d21c8)

**Comment by alanlivio** [comment]
many thanks @sskras. 

It worked in a pure msys2 environment and in a msys2 created from WSL.

![image](https://github.com/msys2/msys2-runtime/assets/604808/b0a0b541-a7e3-4d8e-a3a9-050ace88cb7b)

![image](https://github.com/msys2/msys2-runtime/assets/604808/dd61fa93-9a15-4bb5-a5d9-a260f81e3688)

**Comment by sskras** [comment]
@alanlivio, not at all.  The command still doesn't get you to you WSL home-dir anyway (IOW you still need to run two commands).

I wonder if anything changes if you swap the last two commands:
```sh
$ cd '\\wsl.localhost\Ubuntu\home\alan'
$ cmd.exe /c "C:\msys64\msys2_shell.cmd -defterm -mingw64 -no-start -use-full-path -here"
```

EDIT: Nevermind, accessing UNC paths / Windows shares requires to mount them in WSL:
https://askubuntu.com/questions/1397506/access-windows-network-shares-from-ubuntu-shell-in-wsl/1397507#1397507
... so that won't work. Sorry for the noise.

**Comment by sskras** [comment]
@Biswa96:

> The "UNC paths are not supported" warning is coming from WSL and Windows path conversion. 

Yes, you already wrote that [in a comment above](#issuecomment-1619063256).

> cygwin or msys2 is not related to that. The current directory in WSL is `~` i.e. home directory. It translates to `\\wsl.localhost\Ubuntu\home\alan` in OP's case.

I disagree.  MSYS2 relation is following – it implemented `msys2_shell.cmd` as a way to bootstrap the environment.  The latter is based on CMD and involves the UNC limitation you mentioned already.

So it's the MSYS2 decision to use the limiting technology (instead of using eg. [WSH technology](https://devblogs.microsoft.com/scripting/how-can-i-open-a-window-to-a-unc-location/#:~:text=opening%20a%20window%20to%20a%20UNC%20location)).
It leads to the 2nd argument being not passed-through to the final environment (MINGW64).

That's the issue.

> The above warning can be resolved when the current working directory is a Windows directory. For example, in this screenshot, I invoked the msys2_shell.cmd script in `C:\` directory i.e. `/mnt/c/` in WSL by-default. And it does not show the warning message.

Yes but IMO the aim is not to avoid the warning.
The aim is to get into UNC dir like `\\wsl.localhost\Ubuntu\home\alan` automatically, in a scripted way.

Hence the bugreport. I hope @alanlivio will correct me if I got this wrong.
