### ISSUE TITLE
changes in ~/.profile are useless

### ISSUE THREAD

**Issue by asd-a** [msys2/Cygwin#169]
i add `echo 1` to ~/.profile, but there is no difference

**Comment by sskras** [comment]
Since `.bash_profile` is present, the `.profile` is used only by Bourne-like, POSIX shells, eg. Dash:
https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/

![image](https://github.com/msys2/msys2-runtime/assets/7887758/f1c25265-3c36-4568-a403-e5e3db84b290)

Another explanation:
https://superuser.com/questions/183870/difference-between-bashrc-and-bash-profile/1136289#1136289

![image](https://github.com/msys2/msys2-runtime/assets/7887758/b6e8a765-1525-4198-b715-1a8759399b3c)

So this file would only be used in case a Bourne-like shell (eg. Dash) is start both as login and as an interactive shell.

Eg. by pointing your default user shell to Dash:

![image](https://github.com/msys2/msys2-runtime/assets/7887758/a7ade6d2-a14d-4d0d-b8ce-3e65bc0a03c5)

**Comment by lazka** [comment]
Thanks for the summary.

I checked what other distros provide, and Ubuntu adds a .profile which internally checks if it's run by bash, and Arch only adds a .bash_profile like us.

So in theory we could move new users to .profile instead like Ubuntu, but unless there are real problems that's probably not worth it.

**Comment by sskras** [comment]
Yes, there are many ways (at least some strategies) on how to implement that.
Only a few of them are trying to be cross-platform compatible.

---

Eg. my own strategy is to create and maintain a set of these shell initialization dot-files so it (the set) works on a variety of platforms by rewriting (due to possible copyright issues) large parts of their default files:

- many Linux distros
- Cygwin
- Midipix
- NetBSD and FreeBSD
- macOS and PureDarwin
- Solarish distros
- HP-UX
- maybe AIX and QNX Neutrino (given enough luck:)

---

I guess being compatible with at least some of these is a worth of a separate project.
And yes, migrating from one existing layout to another one (like Arch => Ubuntu) would probably be an easier task.

Now I would do that only in case of migrating from Cygwin to a totally different runtime (like Midipix).
